### PR TITLE
composer update

### PR DESCRIPTION
**Pull request by nidhinsubramanian**

### CODE REVIEW

**Comment by soufiene-slimi** [comment]
Hi @spcheema, is this repo dead ?

**Comment by spcheema** [comment]
Hi @soufiene-slimi. It's our official SDK and not dead. Actually we're quite engaged with other priorities and could not get time to look into. I'll have someone to review the PR. Thanks for your contribution.

**Comment by spcheema** [comment]
Hi @nidhinsubramanian 
Thanks for sending the PR. `Guzzle 7.0.1`  or higher version has compatibility issues with `php-http/guzzle6-adapter`. So we can't merge this PR but we will update both packages in the next release. 
Regards
SP Singh

**Comment by soufiene-slimi** [comment]
Hi @nidhinsubramanian, resolved by #5

**Pull request closed without merging**
